// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBDCbcTQ4vhhHVYDi2XlkiG1BBcrf8LxZc',
    appId: '1:393821276990:web:8b84a9dc2265ab67973a6f',
    messagingSenderId: '393821276990',
    projectId: 'blackcoffer-d9c85',
    authDomain: 'blackcoffer-d9c85.firebaseapp.com',
    storageBucket: 'blackcoffer-d9c85.appspot.com',
    measurementId: 'G-RDL664HV7B',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDvJ2vmVWrZPajlDgbu0ExajkaFV6noXKw',
    appId: '1:393821276990:android:66a32bb800e42a89973a6f',
    messagingSenderId: '393821276990',
    projectId: 'blackcoffer-d9c85',
    storageBucket: 'blackcoffer-d9c85.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAHFpU6elJAKE5qs-mDdbu_Y3oY_iMfIFc',
    appId: '1:393821276990:ios:fabf88045c10be92973a6f',
    messagingSenderId: '393821276990',
    projectId: 'blackcoffer-d9c85',
    storageBucket: 'blackcoffer-d9c85.appspot.com',
    iosBundleId: 'com.kapoorbk.blackcoffer',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAHFpU6elJAKE5qs-mDdbu_Y3oY_iMfIFc',
    appId: '1:393821276990:ios:fabf88045c10be92973a6f',
    messagingSenderId: '393821276990',
    projectId: 'blackcoffer-d9c85',
    storageBucket: 'blackcoffer-d9c85.appspot.com',
    iosBundleId: 'com.kapoorbk.blackcoffer',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBDCbcTQ4vhhHVYDi2XlkiG1BBcrf8LxZc',
    appId: '1:393821276990:web:abdbe608f898e13e973a6f',
    messagingSenderId: '393821276990',
    projectId: 'blackcoffer-d9c85',
    authDomain: 'blackcoffer-d9c85.firebaseapp.com',
    storageBucket: 'blackcoffer-d9c85.appspot.com',
    measurementId: 'G-EMYGMJTMV2',
  );
}
